atom.commands.add 'atom-workspace', 'first-item:copy', ->
  editor = atom.workspace.getActiveTextEditor()
  editor.moveToBeginningOfLine()
  editor.moveToEndOfWord()
  editor.moveToBeginningOfWord()
  editor.selectToEndOfWord()
  a = editor.getSelectedText()
  if (a == '\\' or a == '.')
    editor.selectToEndOfWord()
  #console.log(atom.clipboard.read())
  a = editor.getSelectedText()
  editor.moveToEndOfLine()
  editor.insertNewline()
  editor.insertText(a)
  editor.insertText(" ")
